accountapp/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'

urlpatterns = [
    path('create/',ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>',ProjectDetailView.as_view(), name='detail'),
    path('list/',ProjectListView.as_view(), name='list'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/',SubscriptionView.as_view(), name='subscribe'),
    path('list/',SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% include 'head.html' %}
<body style="font-family: 'NanumGothic';">
{% include 'header.html' %}
<hr/>
{% block content %}
{% endblock %}
<hr/>
{% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="pragmatic_footer">
    <div class="pragmatic_footer_button">
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스사항</span>
    </div>
    <div style="margin-top: 1rem;">
        <h6 class="pragmatic_logo">Pragmatic</h6>
    </div>
</div>

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width", initial-scale="1, shrink-to-fit=no">
    <title>Pragmatic</title>
    <!--  BOOTSTRAP LINK  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!--  GOOGLE FONT LINK  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <!-- DEFAULT CSS LINK   -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css'%}">
    <!--  NAVER FONT MARUBURI -->
    <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-gothic.css" rel="stylesheet">
    <!-- GOOGLE MATERIAL ICON   -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
</head>
</head>

templates/header.html
<div class="pragmatic_header">
    <div><h1 class="pragmatic_logo">Pragmatic</h1></div>
    <div class="pragmatic_header_navbar">
        <a class="pragmatic_header_nav" href="{% url 'articleapp:list'%}">
            <span>Articles</span>
        </a>
        <a class="pragmatic_header_nav" href="{% url 'projectapp:list'%}">
            <span>Projects</span>
        </a>
        <a class="pragmatic_header_nav" href="{% url 'subscribeapp:list'%}">
            <span>Subscription</span>
        </a>
        {% if not user.is_authenticated %}
        <a class="pragmatic_header_nav" href="{% url 'accountapp:login'%}?next={{request.path}}">
            <span>login</span>
        </a>
        <a class="pragmatic_header_nav" href="{% url 'accountapp:create'%}?next={{request.path}}">
            <span>SignUp</span>
        </a>
        {% else %}
        <a class="pragmatic_header_nav" href="{% url 'accountapp:detail' pk=user.pk %}">
            <span>MyPage</span>
        </a>
        <a class="pragmatic_header_nav" href="{% url 'accountapp:logout'%}?next={{request.path}}">
            <span>logout</span>
        </a>
        {% endif %}
    </div>
</div>